# Generated by Django 4.1.7 on 2023-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_joiners'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiners',
            name='file',
            field=models.FileField(default='default/path/to/file', upload_to=''),
        ),
    ]
